---
- name: My Playbook
  hosts: demo
  user: ansible
  become: yes
  connection: ssh
  vars:
    pkgname: httpd  # Set the package name you want to install

  tasks:
    - name: Install HTTPD server
      yum:
        name: "{{ pkgname }}"
        state: present

