--- #loops
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: add list of user in node
      user: name='{{item}}' state=present
      with_items:
        - hari
        - vishall
        - pooja
        - okkk

